<link rel="shortcut icon" href="{{ asset('assets/landing/favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ asset('assets/landing/favicon.ico') }}" type="image/x-icon">
<link rel="apple-touch-icon" href="{{ asset('assets/landing/favicon.ico') }}" type="image/x-icon">

<link rel="icon" href="{{ asset('assets/landing/favicon.ico') }}" type="image/x-icon">
<link rel="apple-touch-icon" href="{{ asset('assets/landing/favicon.ico') }}" type="image/x-icon">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet" media="all">


<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="preload" as="style"
      onload="this.rel='stylesheet'" media="all">
<link href="https://fonts.googleapis.com/css?family=Oranienbaum" rel="preload" as="style" onload="this.rel='stylesheet'"
      media="all">
<link href="{{ asset('assets/landing/style.min.css') }}" rel="preload" as="style" onload="this.rel='stylesheet'"
      media="all">
<link href="{{ asset('assets/landing/media.min.css') }}" rel="preload" as="style" onload="this.rel='stylesheet'"
      media="all">
<link href="{{ asset('assets/landing/style_en.css') }}" rel="preload" as="style" onload="this.rel='stylesheet'"
      media="all">
<link href="{{ asset('assets/landing/css/owl.carousel.min.css') }}" rel="preload" as="style"
      onload="this.rel='stylesheet'" media="all">
<link href="{{ asset('assets/landing/css/owl.theme.default.min.css') }}" rel="preload" as="style"
      onload="this.rel='stylesheet'" media="all">
<link href="{{ asset('assets/landing/css/jquery.fancybox.min.css') }}" rel="preload" as="style"
      onload="this.rel='stylesheet'" media="all">
<link href="{{ asset('assets/landing/css/font-awesome.min.css') }}" rel="preload" as="style"
      onload="this.rel='stylesheet'" media="all">
<link href="{{ asset('assets/landing/css/jquery.datetimepicker.css') }}" rel="preload" as="style"
      onload="this.rel='stylesheet'" media="all">


<style>/* Critical Path CSS Generated by Pegasaas Accelerator at https://pegasaas.com/ for https://arenda-mercedes.kiev.ua/ */

    @font-face {
        font-display: swap;
        font-family: 'Open Sans';
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: url(https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFVZ0e.ttf) format('truetype')
    }

    @font-face {
        font-display: swap;
        font-family: 'Open Sans';
        font-display: swap;
        font-style: normal;
        font-weight: 600;
        src: url(https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOUuhs.ttf) format('truetype')
    }

    @font-face {
        font-display: swap;
        font-family: 'Open Sans';
        font-style: normal;
        font-display: swap;
        font-weight: 700;
        src: url(https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOUuhs.ttf) format('truetype')
    }

    @font-face {
        font-display: swap;
        font-family: Oranienbaum;
        font-style: normal;
        font-weight: 400;
        src: url(https://fonts.gstatic.com/s/oranienbaum/v9/OZpHg_txtzZKMuXLIVrx-0zg5Eg.ttf) format('truetype')
    }

    html {
        font-family: sans-serif
    }

    body {
        margin: 0px
    }

    footer, header, nav, section {
        display: block
    }

    video {
        display: inline-block;
        vertical-align: baseline
    }

    a {
        background-color: transparent
    }

    strong {
        font-weight: bold
    }

    h1 {
        font-size: 2em;
        margin: 0.67em 0px
    }

    img {
        border: 0px
    }

    hr {
        box-sizing: content-box;
        height: 0px
    }

    button, input, textarea {
        color: inherit;
        font-family: inherit;
        font-size: inherit;
        font-style: inherit;
        font-variant: inherit;
        font-weight: inherit;
        line-height: inherit;
        margin: 0px
    }

    button {
        overflow: visible
    }

    button {
        text-transform: none
    }

    button, input[type="submit"] {
        -webkit-appearance: button
    }

    input {
        line-height: normal
    }

    input[type="checkbox"] {
        box-sizing: border-box;
        padding: 0px
    }

    textarea {
        overflow: auto
    }

    table {
        border-collapse: collapse;
        border-spacing: 0px
    }

    td {
        padding: 0px
    }

    * {
        box-sizing: border-box
    }

    ::before, ::after {
        box-sizing: border-box
    }

    html {
        font-size: 10px
    }

    body {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 14px;
        line-height: 1.42857143;
        color: rgb(51, 51, 51);
        background-color: rgb(255, 255, 255)
    }

    input, button, textarea {
        font-family: inherit;
        font-size: inherit;
        line-height: inherit
    }

    a {
        color: rgb(66, 139, 202);
        text-decoration: none
    }

    img {
        vertical-align: middle
    }

    .img-responsive {
        display: block;
        max-width: 100%;
        height: auto
    }

    hr {
        margin-top: 20px;
        margin-bottom: 20px;
        border-width: 1px 0px 0px;
        border-top-style: solid;
        border-top-color: rgb(238, 238, 238)
    }

    .sr-only {
        position: absolute;
        width: 1px;
        height: 1px;
        margin: -1px;
        padding: 0px;
        overflow: hidden;
        clip: rect(0px 0px 0px 0px);
        border: 0px
    }

    h1, h2, h4 {
        font-family: inherit;
        font-weight: 500;
        line-height: 1.1;
        color: inherit
    }

    h1, h2 {
        margin-top: 20px;
        margin-bottom: 10px
    }

    h4 {
        margin-top: 10px;
        margin-bottom: 10px
    }

    h1 {
        font-size: 36px
    }

    h2 {
        font-size: 30px
    }

    h4 {
        font-size: 18px
    }

    p {
        margin: 0px 0px 10px
    }

    .text-center {
        text-align: center
    }

    ul {
        margin-top: 0px;
        margin-bottom: 10px
    }

    ul ul {
        margin-bottom: 0px
    }

    .container {
        margin-right: auto;
        margin-left: auto;
        padding-left: 15px;
        padding-right: 15px
    }

    @media (min-width: 768px) {
        .container {
            width: 750px
        }
    }

    @media (min-width: 992px) {
        .container {
            width: 970px
        }
    }

    @media (min-width: 1200px) {
        .container {
            width: 1170px
        }
    }

    .container-fluid {
        margin-right: auto;
        margin-left: auto;
        padding-left: 15px;
        padding-right: 15px
    }

    .row {
        margin-left: -15px;
        margin-right: -15px
    }

    .col-sm-1, .col-sm-2, .col-sm-3, .col-lg-3, .col-xs-4, .col-md-4, .col-xs-5, .col-sm-5, .col-sm-6, .col-lg-6, .col-sm-7, .col-md-8, .col-lg-8, .col-md-10, .col-sm-11, .col-xs-12 {
        position: relative;
        min-height: 1px;
        padding-left: 15px;
        padding-right: 15px
    }

    .col-xs-4, .col-xs-5, .col-xs-12 {
        float: left
    }

    .col-xs-12 {
        width: 100%
    }

    .col-xs-5 {
        width: 41.66666667%
    }

    .col-xs-4 {
        width: 33.33333333%
    }

    @media (min-width: 768px) {
        .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-11 {
            float: left
        }

        .col-sm-11 {
            width: 91.66666667%
        }

        .col-sm-7 {
            width: 58.33333333%
        }

        .col-sm-6 {
            width: 50%
        }

        .col-sm-5 {
            width: 41.66666667%
        }

        .col-sm-3 {
            width: 25%
        }

        .col-sm-2 {
            width: 16.66666667%
        }

        .col-sm-1 {
            width: 8.33333333%
        }
    }

    @media (min-width: 992px) {
        .col-md-4, .col-md-8, .col-md-10 {
            float: left
        }

        .col-md-10 {
            width: 83.33333333%
        }

        .col-md-8 {
            width: 66.66666667%
        }

        .col-md-4 {
            width: 33.33333333%
        }

        .col-md-offset-2 {
            margin-left: 16.66666667%
        }
    }

    @media (min-width: 1200px) {
        .col-lg-3, .col-lg-6, .col-lg-8 {
            float: left
        }

        .col-lg-8 {
            width: 66.66666667%
        }

        .col-lg-6 {
            width: 50%
        }

        .col-lg-3 {
            width: 25%
        }

        .col-lg-offset-2 {
            margin-left: 16.66666667%
        }
    }

    table {
        background-color: transparent
    }

    label {
        display: inline-block;
        max-width: 100%;
        margin-bottom: 5px;
        font-weight: bold
    }

    input[type="checkbox"] {
        margin: 4px 0px 0px;
        line-height: normal
    }

    .form-control {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: rgb(85, 85, 85);
        background-color: rgb(255, 255, 255);
        background-image: none;
        border: 1px solid rgb(204, 204, 204);
        border-top-left-radius: 4px;
        border-top-right-radius: 4px;
        border-bottom-right-radius: 4px;
        border-bottom-left-radius: 4px;
        -webkit-box-shadow: rgba(0, 0, 0, 0.0745098) 0px 1px 1px inset;
        box-shadow: rgba(0, 0, 0, 0.0745098) 0px 1px 1px inset
    }

    .form-control::-webkit-input-placeholder {
        color: rgb(153, 153, 153)
    }

    .form-group {
        margin-bottom: 15px
    }

    .collapse {
        display: none
    }

    .nav {
        margin-bottom: 0px;
        padding-left: 0px;
        list-style: none
    }

    .nav > li {
        position: relative;
        display: block
    }

    .nav > li > a {
        position: relative;
        display: block;
        padding: 10px 15px
    }

    .navbar {
        position: relative;
        min-height: 50px;
        margin-bottom: 20px;
        border: 1px solid transparent
    }

    @media (min-width: 768px) {
        .navbar {
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
            border-bottom-right-radius: 4px;
            border-bottom-left-radius: 4px
        }
    }

    @media (min-width: 768px) {
        .navbar-header {
            float: left
        }
    }

    .navbar-collapse {
        overflow-x: visible;
        padding-right: 15px;
        padding-left: 15px;
        border-top-width: 1px;
        border-top-style: solid;
        border-top-color: transparent;
        -webkit-box-shadow: rgba(255, 255, 255, 0.0980392) 0px 1px 0px inset;
        box-shadow: rgba(255, 255, 255, 0.0980392) 0px 1px 0px inset
    }

    @media (min-width: 768px) {
        .navbar-collapse {
            width: auto;
            border-top-width: 0px;
            -webkit-box-shadow: none;
            box-shadow: none
        }

        .navbar-collapse.collapse {
            padding-bottom: 0px;
            display: block !important;
            height: auto !important;
            overflow: visible !important
        }

        .navbar-fixed-top .navbar-collapse {
            padding-left: 0px;
            padding-right: 0px
        }
    }

    .navbar-fixed-top .navbar-collapse {
        max-height: 340px
    }

    @media (max-device-width: 480px) and (orientation: landscape) {
        .navbar-fixed-top .navbar-collapse {
            max-height: 200px
        }
    }

    .container > .navbar-header, .container > .navbar-collapse {
        margin-right: -15px;
        margin-left: -15px
    }

    @media (min-width: 768px) {
        .container > .navbar-header, .container > .navbar-collapse {
            margin-right: 0px;
            margin-left: 0px
        }
    }

    .navbar-fixed-top {
        position: fixed;
        right: 0px;
        left: 0px;
        z-index: 1030
    }

    @media (min-width: 768px) {
        .navbar-fixed-top {
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-right-radius: 0px;
            border-bottom-left-radius: 0px
        }
    }

    .navbar-fixed-top {
        top: 0px;
        border-width: 0px 0px 1px
    }

    .navbar-brand {
        float: left;
        padding: 15px;
        font-size: 18px;
        line-height: 20px;
        height: 50px
    }

    .navbar-brand > img {
        display: block
    }

    @media (min-width: 768px) {
        .navbar > .container .navbar-brand {
            margin-left: -15px
        }
    }

    .navbar-nav {
        margin: 7.5px -15px
    }

    .navbar-nav > li > a {
        padding-top: 10px;
        padding-bottom: 10px;
        line-height: 20px
    }

    @media (min-width: 768px) {
        .navbar-nav {
            float: left;
            margin: 0px
        }

        .navbar-nav > li {
            float: left
        }

        .navbar-nav > li > a {
            padding-top: 15px;
            padding-bottom: 15px
        }
    }

    @media (min-width: 768px) {
        .navbar-right {
            margin-right: -15px;
            float: right !important
        }

        .navbar-right ~ .navbar-right {
            margin-right: 0px
        }
    }

    .navbar-default {
        background-color: rgb(248, 248, 248);
        border-color: rgb(231, 231, 231)
    }

    .navbar-default .navbar-brand {
        color: rgb(119, 119, 119)
    }

    .navbar-default .navbar-nav > li > a {
        color: rgb(119, 119, 119)
    }

    .navbar-default .navbar-collapse {
        border-color: rgb(231, 231, 231)
    }

    .clearfix::before, .clearfix::after, .container::before, .container::after, .container-fluid::before, .container-fluid::after, .row::before, .row::after, .nav::before, .nav::after, .navbar::before, .navbar::after, .navbar-header::before, .navbar-header::after, .navbar-collapse::before, .navbar-collapse::after {
        content: ' ';
        display: table
    }

    .clearfix::after, .container::after, .container-fluid::after, .row::after, .nav::after, .navbar::after, .navbar-header::after, .navbar-collapse::after {
        clear: both
    }

    .hidden {
        display: none !important
    }

    .visible-xs, .visible-sm, .visible-lg {
        display: none !important
    }

    @media (max-width: 767px) {
        .visible-xs {
            display: block !important
        }
    }

    @media (max-width: 991px) and (min-width: 768px) {
        .visible-sm {
            display: block !important
        }
    }

    @media (min-width: 1200px) {
        .visible-lg {
            display: block !important
        }
    }

    @media (max-width: 767px) {
        .hidden-xs {
            display: none !important
        }
    }

    @media (max-width: 991px) and (min-width: 768px) {
        .hidden-sm {
            display: none !important
        }
    }

    @font-face {
        font-display: swap;
        font-family: 'Yanone Kaffeesatz';
        src: local(☺), url(/assets/landing/fonts/YanoneKaffeesatz-Bold.woff) format('woff'), url(/assets/landing/fonts/YanoneKaffeesatz-Bold.ttf) format('truetype'), url(/assets/landing/fonts/YanoneKaffeesatz-Bold.svg) format('svg');
        font-weight: normal;
        font-style: normal
    }

    html, body, div, span, iframe, h1, h2, h4, p, a, img, strong, i, ul, li, form, label, table, tbody, tr, td, footer, header, nav, section, video {
        margin: 0px;
        padding: 0px;
        border: 0px;
        font-family: inherit;
        font-size: inherit;
        font-style: inherit;
        font-variant: inherit;
        font-weight: inherit;
        line-height: inherit;
        vertical-align: baseline
    }

    footer, header, nav, section {
        display: block
    }

    body {
        font-size: 14px;
        text-shadow: rgba(0, 0, 0, 0.498039) 0px 0px 0px;
        line-height: 24px !important;
        font-family: 'open sans', sans-serif !important
    }

    ul {
        list-style: none
    }

    table {
        border-collapse: collapse;
        border-spacing: 0px
    }

    h1 {
        font-weight: 700 !important;
        font-style: normal !important;
        font-variant: normal !important;
        font-size: 70px !important;
        line-height: normal !important;
        font-family: 'Yanone Kaffeesatz', sans-serif !important
    }

    h2 {
        text-transform: uppercase;
        font-weight: 700 !important;
        font-style: normal !important;
        font-variant: normal !important;
        font-size: 40px !important;
        line-height: normal !important;
        font-family: 'Yanone Kaffeesatz', sans-serif !important
    }

    h4 {
        font-weight: 600 !important;
        font-style: normal !important;
        font-variant: normal !important;
        font-size: 24px !important;
        line-height: normal !important;
        font-family: 'open sans', sans-serif !important
    }

    hr {
        border-color: rgb(22, 22, 22)
    }

    strong {
        font-weight: 700;
        color: rgb(22, 22, 22)
    }

    a:visited {
        outline: none !important;
        text-decoration: none !important
    }

    .yellow {
        color: rgb(253, 194, 16)
    }

    .black {
        color: rgb(22, 22, 22)
    }

    .white {
        color: rgb(255, 255, 255)
    }

    .navbar-default {
        background-color: rgb(17, 23, 26) !important
    }

    .navbar {
        border: 0px
    }

    .navmenu a.active {
        color: rgb(253, 194, 16) !important
    }

    .call li a {
        padding: 12px 20px;
        text-transform: uppercase;
        font-weight: bold;
        font-style: normal;
        font-variant: normal;
        font-size: 20px;
        line-height: normal;
        font-family: 'Yanone Kaffeesatz', sans-serif;
        border: 1px solid transparent;
        background-image: linear-gradient(to top, rgb(237, 178, 1), rgb(249, 191, 13), rgb(255, 206, 28)) !important;
        color: rgb(9, 9, 9) !important;
        background-position: initial initial !important;
        background-repeat: initial initial !important
    }

    .main_block {
        margin: 16% 0px 8%
    }

    .main_block h1 {
        text-transform: uppercase
    }

    .main_block .rent {
        margin: 20px 0px
    }

    .main_block .rent img {
        float: left;
        margin-right: 42px
    }

    .main_block > .rent > p {
        font-style: normal;
        font-variant: normal;
        font-weight: normal;
        font-size: 62px;
        line-height: normal;
        font-family: Oranienbaum, serif;
        position: relative;
        bottom: 4px
    }

    .main_block > p {
        color: rgb(204, 203, 203);
        font-size: 30px;
        font-weight: 600
    }

    .slide_bg .info {
        background-color: rgba(0, 0, 0, 0.34902);
        position: relative;
        z-index: 1
    }

    .slide_bg .info .sq_bg {
        background-image: url(/assets/landing/images/sqimg.webp);
        height: 104px;
        margin: 43px 0px;
        padding-top: 18px;
        background-position: 15px 50%;
        background-repeat: no-repeat no-repeat
    }

    .slide_bg .info .sq_bg p {
        color: rgb(255, 255, 255);
        font-size: 18px;
        font-weight: 600;
        line-height: 32px
    }

    .slide_bg .info .sq_bg p::after {
        content: '';
        background-image: url(/assets/landing/images/gimg.webp);
        height: 12px;
        width: 16px;
        display: inline-block;
        margin-left: 15px;
        background-position: initial initial;
        background-repeat: no-repeat no-repeat
    }

    .about_bg {
        background-color: rgb(229, 229, 229);
        position: relative;
        z-index: 1
    }

    .about_bg .about {
        margin-top: 65px;
        margin-bottom: 10px
    }

    .about_bg .about h2 {
        margin-bottom: 25px
    }

    .about_bg .block_how {
        background-image: url(/assets/landing/images/about_bg.webp);
        height: 286px;
        position: absolute;
        width: 1170px;
        bottom: 0px;
        left: 0px;
        background-position: initial initial;
        background-repeat: no-repeat no-repeat
    }

    .block_li {
        background-color: rgb(253, 194, 16);
        position: relative;
        font-size: 16px;
        font-weight: 600;
        box-shadow: rgb(0, 0, 0) 0px 34px 50px -45px
    }

    .block_li .li_right li {
        text-align: right
    }

    .block_li .li_right, .block_li .li_left {
        margin: 20px 0px
    }

    .block_li .li_right li, .block_li .li_left li {
        margin-bottom: 10px
    }

    .block_li .li_left li::before {
        content: '';
        background-image: url(/assets/landing/images/ok.webp);
        height: 16px;
        width: 15px;
        margin-right: 10px;
        display: inline-block;
        position: relative;
        top: 2px;
        background-position: initial initial;
        background-repeat: no-repeat no-repeat
    }

    .block_li .li_right li::after {
        content: '';
        background-image: url(/assets/landing/images/ok.webp);
        height: 16px;
        width: 15px;
        margin-left: 10px;
        display: inline-block;
        position: relative;
        top: 2px;
        background-position: initial initial;
        background-repeat: no-repeat no-repeat
    }

    .mission {
        display: inline-block;
        margin-top: 20px;
        margin-bottom: 20px
    }

    .gallery_bg {
        background-color: rgb(0, 0, 0)
    }

    .block_cars {
        margin: 35px 0px
    }

    .block_cars h2 {
        margin-bottom: 13px
    }

    nav.menu_cars {
        margin-top: 24px
    }

    nav.menu_cars button {
        display: inline-block;
        margin: 0px 10px;
        text-transform: uppercase;
        color: rgb(253, 194, 16);
        padding: 8px 18px;
        font-size: 18px;
        font-weight: 600;
        background-image: none;
        border: none;
        outline: none;
        background-position: initial initial;
        background-repeat: initial initial
    }

    nav.menu_cars button.current {
        background-color: rgb(204, 203, 203);
        color: rgb(42, 44, 43)
    }

    .gallery_bg .more button {
        margin: 30px 0px 40px;
        padding: 12px 40px;
        font-weight: 700;
        font-style: normal;
        font-variant: normal;
        font-size: 30px;
        line-height: normal;
        font-family: 'Yanone Kaffeesatz', sans-serif;
        text-transform: uppercase;
        border: 1px solid transparent;
        outline: none;
        background-image: linear-gradient(to top, rgb(237, 178, 1), rgb(249, 191, 13), rgb(255, 206, 28)) !important;
        background-position: initial initial !important;
        background-repeat: initial initial !important
    }

    .job_bg {
        background-image: url(/assets/landing/images/cars.bg.webp);
        background-size: cover;
        height: 580px;
        background-position: 50% 100%;
        background-repeat: no-repeat no-repeat
    }

    .job_bg h2 {
        margin: 63px 0px 30px
    }

    .dots {
        position: absolute;
        top: 37px;
        right: -11px
    }

    .faq_bg {
        background-image: url(/assets/landing/images/faq_bg.webp);
        background-size: cover;
        height: 750px;
        background-position: 50% 50%;
        background-repeat: no-repeat no-repeat
    }

    .faq_wrap h2 {
        margin: 8% 0px 3%
    }

    .faq_wrap td {
        vertical-align: middle;
        color: rgb(255, 255, 255);
        padding-bottom: 20px
    }

    .faq_wrap td.left {
        padding-right: 20px;
        vertical-align: top;
        padding-top: 7px
    }

    .faq_wrap td span {
        font-size: 18px;
        font-weight: 600
    }

    .review_bg {
        background-color: rgb(204, 203, 203)
    }

    .review_wrap h2 {
        margin: 65px 0px 13px
    }

    .review_wrap .owl-carousel {
        margin-bottom: 5%
    }

    .review_bg .owl-carousel .owl-item {
        opacity: 0.5
    }

    .review_bg .owl-carousel .owl-item.center {
        opacity: 1
    }

    .review_bg .owl-carousel .owl-item.center img {
        width: 160px;
        height: 160px;
        margin: 0px auto;
        border: 1px solid rgb(0, 0, 0);
        border-top-left-radius: 100px;
        border-top-right-radius: 100px;
        border-bottom-right-radius: 100px;
        border-bottom-left-radius: 100px
    }

    .review_bg .owl-carousel .owl-item img {
        width: 130px;
        height: 130px;
        margin: 15px auto;
        border: 1px solid gray;
        border-top-left-radius: 100px;
        border-top-right-radius: 100px;
        border-bottom-right-radius: 100px;
        border-bottom-left-radius: 100px
    }

    .cap {
        visibility: hidden
    }

    .cap h4 {
        margin-bottom: 15px
    }

    .review_bg .owl-carousel .owl-item.center .cap {
        visibility: visible
    }

    .owl-theme .owl-dots .owl-dot span {
        border: 1px solid rgb(0, 0, 0);
        background-color: rgb(22, 22, 22) !important
    }

    .owl-theme .owl-dots .owl-dot.active span {
        border: 1px solid rgb(0, 0, 0);
        background-color: rgb(253, 194, 16) !important
    }

    .contacts_bg {
        background-image: url(/assets/landing/images/contacts_bg.webp);
        background-size: cover;
        background-position: 50% 50%;
        background-repeat: no-repeat no-repeat
    }

    .map_wrap {
        position: relative
    }

    .contact {
        width: 380px;
        background-color: rgb(253, 194, 16);
        position: absolute;
        top: 90px;
        left: -180px;
        padding: 32px 35px;
        box-shadow: rgb(0, 0, 0) 0px 45px 45px -40px
    }

    .map_wrap .contact input {
        width: 100%;
        height: 40px;
        border: 0px;
        border-top-left-radius: 0px;
        border-top-right-radius: 0px;
        border-bottom-right-radius: 0px;
        border-bottom-left-radius: 0px;
        text-indent: 35px;
        color: rgb(0, 0, 0)
    }

    .map_wrap .contact h2 {
        margin-bottom: 18px
    }

    .map_wrap .contact .form-group {
        position: relative;
        margin-bottom: 17px !important
    }

    .map_wrap .contact .form-group i {
        position: absolute;
        top: 5px;
        z-index: 1;
        border-right-width: 1px;
        border-right-style: solid;
        border-right-color: rgb(204, 203, 203);
        padding: 8px 16px;
        width: 40px;
        color: rgb(204, 203, 203);
        background-color: rgb(255, 255, 255)
    }

    .map_wrap .contact input[type="submit"] {
        height: 60px;
        color: rgb(255, 255, 255);
        background-color: rgb(8, 9, 9);
        font-weight: bold;
        font-style: normal;
        font-variant: normal;
        font-size: 30px;
        line-height: normal;
        font-family: 'Yanone Kaffeesatz', sans-serif;
        text-transform: uppercase;
        text-indent: 0px;
        border: 1px solid transparent
    }

    .map_wrap .contact input::-webkit-input-placeholder {
        color: rgb(22, 22, 22);
        text-shadow: rgb(0, 0, 0) 0px 1px 0px
    }

    .map_wrap .information::before {
        content: '';
        position: absolute;
        left: -30px;
        top: 80px;
        border-width: 15px;
        border-style: solid;
        border-color: transparent black transparent transparent
    }

    .map_wrap .information {
        width: 320px;
        position: absolute;
        top: 115px;
        right: 90px;
        background-color: rgb(0, 0, 0)
    }

    .map_wrap .information table {
        margin: 13px 0px
    }

    .map_wrap .information td {
        vertical-align: middle;
        padding: 10px 5px;
        font-size: 16px;
        color: rgb(255, 255, 255)
    }

    .map_wrap .information td a {
        color: rgb(255, 255, 255)
    }

    .map_wrap .information td img {
        position: relative;
        top: 5px
    }

    .map_wrap .information td.l_img {
        vertical-align: top
    }

    .map_wrap .information td span {
        font-size: 14px
    }

    footer {
        background-color: rgb(17, 23, 26)
    }

    footer li {
        display: inline-block;
        margin-right: 20px
    }

    footer li a, footer p {
        color: rgb(255, 255, 255)
    }

    footer li a {
        text-transform: uppercase
    }

    footer li a i {
        font-size: 30px !important
    }

    footer p {
        font-size: 12px;
        margin-top: 10px
    }

    footer .footer_menu {
        margin: 2% 0px 1.8%
    }

    footer .footer_social {
        text-align: right;
        margin: 3% 0px;
        padding-right: 75px
    }

    #more.hiddens {
        visibility: hidden;
        overflow: hidden
    }

    #hidden-call, #hidden-order {
        background-color: rgb(253, 194, 16)
    }

    .contact_us {
        width: 350px;
        padding: 10px 10px 0px
    }

    #hidden-order .order {
        width: 630px
    }

    #hidden-order input.subm_order {
        width: 50%
    }

    .contact_us input {
        width: 100%;
        height: 40px;
        border: 0px;
        border-top-left-radius: 0px;
        border-top-right-radius: 0px;
        border-bottom-right-radius: 0px;
        border-bottom-left-radius: 0px;
        text-indent: 40px;
        color: rgb(0, 0, 0)
    }

    .contact_us h2 {
        margin-bottom: 18px
    }

    .contact_us .form-group {
        position: relative;
        margin-bottom: 17px !important
    }

    .contact_us .form-group i {
        position: absolute;
        top: 5px;
        z-index: 1;
        border-right-width: 1px;
        border-right-style: solid;
        border-right-color: rgb(204, 203, 203);
        padding: 8px 11px 8px 13px;
        color: rgb(204, 203, 203);
        width: 43px;
        text-align: center;
        background-color: rgb(255, 255, 255)
    }

    .contact_us input[type="submit"] {
        height: 60px;
        color: rgb(255, 255, 255);
        background-color: rgb(8, 9, 9);
        font-weight: bold;
        font-style: normal;
        font-variant: normal;
        font-size: 30px;
        line-height: normal;
        font-family: 'Yanone Kaffeesatz', sans-serif;
        text-transform: uppercase;
        text-indent: 0px
    }

    .contact_us textarea {
        width: 100%;
        border: 0px;
        padding: 8px;
        outline: none;
        border-top-left-radius: 0px;
        border-top-right-radius: 0px;
        border-bottom-right-radius: 0px;
        border-bottom-left-radius: 0px;
        text-indent: 44px !important
    }

    .contact_us input::-webkit-input-placeholder {
        color: rgb(22, 22, 22)
    }

    .contact_us textarea::-webkit-input-placeholder {
        color: rgb(22, 22, 22);
        text-indent: 44px
    }

    textarea {
        resize: none
    }

    .phones .lang {
        margin-top: 3px;
        padding-bottom: 0px;
        color: rgb(255, 255, 255)
    }

    .phones .lang i {
        margin-left: 5px
    }

    .phones .down {
        display: none;
        z-index: 1
    }

    .phones .down li {
        padding: 0px 7px;
        background-color: rgb(253, 194, 16);
        width: 33px;
        color: rgb(0, 0, 0) !important;
        margin-right: 23px !important;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .window .header .icon img {
        position: relative;
        top: 8px
    }

    .window {
        position: relative;
        display: block;
        width: 100%;
        height: 50px;
        box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 65px 15px;
        overflow: hidden;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
        border-bottom-right-radius: 3px;
        border-bottom-left-radius: 3px;
        background-color: rgb(241, 241, 241);
        background-position: initial initial;
        background-repeat: initial initial
    }

    .window .header {
        position: absolute;
        display: block;
        top: 0px;
        left: 0px;
        height: 50px;
        width: 100%;
        background-color: rgba(0, 0, 0, 0.8);
        overflow: hidden;
        z-index: 1;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .window .header .burger-container {
        position: relative;
        display: inline-block;
        height: 50px;
        width: 50px;
        -webkit-transform: rotate(0deg)
    }

    .window .header .burger-container #burger {
        width: 18px;
        height: 8px;
        position: relative;
        display: block;
        margin: -4px auto 0px;
        top: 50%
    }

    .window .header .burger-container #burger .bar {
        width: 100%;
        height: 1px;
        display: block;
        position: relative;
        background-color: rgb(255, 255, 255);
        background-position: initial initial;
        background-repeat: initial initial
    }

    .window .header .icon {
        display: inline-block;
        position: absolute;
        line-height: 50px;
        width: 200px;
        height: 50px;
        text-align: center;
        color: rgb(255, 255, 255);
        font-size: 22px;
        left: 50%;
        -webkit-transform: translateX(-50%)
    }

    .window .header .icon.icon-bag {
        right: 0px;
        top: 0px;
        left: auto;
        -webkit-transform: translateX(0px)
    }

    .window .header ul.menu {
        position: relative;
        display: block;
        padding: 0px 48px;
        list-style: none
    }

    .window .header ul.menu li.menu-item {
        border-bottom-width: 1px;
        border-bottom-style: solid;
        border-bottom-color: rgb(51, 51, 51);
        margin-top: 5px;
        -webkit-transform: scale(1.15) translateY(-30px);
        opacity: 0
    }

    .window .header ul.menu li.menu-item a {
        display: block;
        position: relative;
        color: rgb(255, 255, 255);
        font-family: 'Ek Mukta', sans-serif;
        text-decoration: none;
        font-size: 22px;
        line-height: 2.35;
        font-weight: 200;
        width: 100%
    }

    @media (max-width: 767px) {
        .window {
            width: 100%;
            height: 50px;
            margin: 0px;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-right-radius: 0px;
            border-bottom-left-radius: 0px
        }

        .window .header {
            position: fixed
        }
    }

    @media (max-width: 425px) {
        .navbar-fixed-top {
            position: fixed !important
        }
    }

    .result {
        color: rgb(0, 0, 0);
        margin-bottom: 23px;
        font-size: 16px;
        text-align: center;
        font-weight: bold !important
    }

    input[type="tel"], input[type="text"], input[type="email"], textarea {
        font-size: 15px !important
    }

    .contact_us input[type="checkbox"] {
        width: 30px;
        height: 30px;
        background-color: rgb(255, 255, 255);
        background-image: none;
        border: none;
        box-shadow: rgba(0, 0, 0, 0.0745098) 0px 1px 1px inset
    }

    .driver-label {
        padding-top: 6px;
        font-weight: bold
    }

    .catalog_img_item lazyload {
        min-height: 230px;
        background-size: cover;
        background-repeat: no-repeat no-repeat
    }

    #more {
        height: 0px
    }

    .video_wrap {
        margin-bottom: 20px
    }

    .video_wrap video {
        width: 100%
    }

    @media (max-width: 768px) {
        .contact_us .col-sm-1 {
            position: absolute;
            top: 0px;
            left: 0px
        }

        .driver-label {
            padding-left: 60px
        }
    }

    @media (max-width: 991px) {
        .slide_bg {
            background: black !important;;
            background-size: cover;
            background-position: 5% 50%;
            background-repeat: no-repeat no-repeat
        }
    }

    @media (max-width: 475px) {
        .slide_bg {
            background: black !important;;
            background-size: cover;
            background-position: 15% 50%;
            background-repeat: no-repeat no-repeat
        }
    }

    @media (min-width: 1200px) {
        .navbar-brand {
            height: inherit;
            padding: 20px 15px 25px
        }

        .phones li {
            padding-top: 15px;
            padding-bottom: 10px;
            margin-right: 16px;
            color: rgb(172, 172, 173)
        }

        .phones li a {
            padding: 0px;
            display: inline-block;
            font-size: 12px;
            color: rgb(172, 172, 173) !important
        }

        .call {
            margin: 26px 0px 26px 20px
        }

        .phones li img {
            position: relative;
            top: 5px;
            margin-right: 5px
        }

        .navmenu > li > a {
            text-transform: uppercase;
            font-weight: bold;
            padding: 10px 12px !important;
            color: rgb(255, 255, 255) !important
        }

        .main_block {
            padding-left: 44px
        }

        .block {
            padding: 10px 0px 36px
        }

        .block_li .li_right li {
            text-align: right;
            padding-right: 45px
        }

        .block_li .li_left li {
            padding-left: 50px
        }

        .block_li .li_right, .block_li .li_left {
            margin: 41px 0px 19px
        }

        .block_li .li_right li, .block_li .li_left li {
            margin-bottom: 16px
        }

        .about_bg .about {
            padding: 0px
        }

        .mission {
            padding-left: 40px;
            margin-bottom: 47px;
            margin-top: 0px
        }

        .mission p {
            margin-bottom: 12px
        }

        .block_cars {
            margin: 64px 0px 0px
        }

        .block_cars h2 {
            margin-bottom: 13px
        }

        nav.menu_cars {
            margin: 24px 0px 40px
        }

        .gallery_bg .more button {
            margin: 55px 0px 65px;
            padding: 12px 110px
        }

        .jobs {
            position: relative;
            left: 9%
        }

        .faq_wrap table {
            position: relative;
            left: 30px
        }

        .cap .text {
            min-height: 150px;
            max-height: 150px;
            overflow: hidden;
            margin-bottom: 20px
        }

        .review_bg .owl-carousel .owl-item.center .cap {
            visibility: visible;
            width: 455%;
            position: relative;
            right: 175%;
            top: 30px
        }

        .map_wrap .information td a[href^="tel"] {
            font-size: 22px !important
        }
    }

    @media (min-width: 1300px) {
        .container_menu {
            width: 1296px
        }

        .call {
            margin: 25px 0px 25px 52px
        }

        .call li a {
            padding: 15px 29px
        }

        .navmenu > li > a {
            padding: 10px 16px !important
        }

        .phones li {
            margin-right: 23px
        }

        .phones li:last-child {
            margin-right: 10px
        }
    }

    @media (max-width: 1199px) and (min-width: 992px) {
        .phones > li > a, .phones li {
            display: inline-block;
            padding: 0px 5px;
            margin-bottom: 5px;
            color: rgb(255, 255, 255) !important
        }

        .navbar-header {
            margin: 24px 0px
        }

        a.navbar-brand {
            display: inline-table
        }

        .call > li > a {
            position: relative;
            right: 230px
        }

        .phones > li > a, .phones li {
            padding: 10px 10px 0px;
            margin-bottom: 0px;
            color: rgb(255, 255, 255) !important
        }

        .phones li img {
            position: relative;
            top: 5px;
            margin-right: 10px
        }

        .phones li:nth-child(3), .phones li:nth-child(4) {
            padding: 15px 10px 0px
        }

        .navmenu > li > a {
            text-transform: uppercase;
            padding: 15px 12px;
            color: rgb(255, 255, 255) !important
        }

        .main_block {
            margin: 18% 0px 4%;
            padding-left: 120px
        }

        .slide_bg .info .sq_bg p {
            font-size: 14px
        }

        .about_bg .about {
            margin-top: 50px
        }

        .dots {
            width: 62%
        }

        .jobs {
            position: relative;
            left: 5%
        }

        .cap .text {
            min-height: 150px;
            max-height: 150px;
            overflow: hidden;
            margin-bottom: 30px
        }

        .review_bg .owl-carousel .owl-item.center .cap {
            visibility: visible;
            width: 250%;
            position: relative;
            right: 75%;
            top: 30px
        }

        .contact {
            left: -173px
        }

        .map_wrap .information {
            right: 0px
        }

        .faq_wrap td {
            padding-bottom: 10px
        }

        .faq_bg {
            background-image: url(/assets/landing/images/faq_bg.webp);
            background-position: 48% 50%;
            background-repeat: no-repeat no-repeat
        }

        #date2 {
            min-width: 270px
        }
    }

    @media (max-width: 991px) and (min-width: 768px) {
        .phones > li > a, .phones li {
            display: inline-block;
            padding: 0px 5px;
            margin-bottom: 5px;
            color: rgb(255, 255, 255) !important
        }

        a.navbar-brand {
            display: inline-table
        }

        .call > li > a {
            position: relative;
            top: 20px;
            right: 125px
        }

        .phones > li > a, .phones li {
            padding: 0px 10px;
            margin-bottom: 0px;
            color: rgb(255, 255, 255) !important
        }

        .phones li img {
            position: relative;
            top: 5px;
            margin-right: 10px
        }

        .phones li:nth-child(3), .phones li:nth-child(4) {
            padding: 0px 10px
        }

        .navmenu > li > a {
            text-transform: uppercase;
            padding: 12px;
            color: rgb(255, 255, 255) !important
        }

        .navbar-brand > img {
            width: 80%
        }

        .call li a {
            padding: 8px 20px
        }

        .main_block {
            margin: 27% 0px 3%
        }

        .slide_bg .info .sm12 {
            background-image: url(/assets/landing/images/sqimg.webp);
            margin-top: 0px;
            background-position: 5% 50%;
            background-repeat: no-repeat no-repeat
        }

        .about_bg .about {
            margin-top: 45px
        }

        .dots {
            width: 50%
        }

        .jobs {
            position: relative;
            left: 4%
        }

        .cap .text {
            min-height: 165px;
            max-height: 165px;
            overflow: hidden;
            margin-bottom: 30px
        }

        .review_bg .owl-carousel .owl-item.center .cap {
            visibility: visible;
            width: 275%;
            position: relative;
            right: 90%;
            top: 30px
        }

        .contact {
            position: relative;
            top: 0px;
            left: 0px;
            box-shadow: none;
            width: 50%
        }

        .map_wrap .information {
            padding-left: 60px;
            position: relative;
            top: 0px;
            right: 0px;
            width: 50%
        }

        .map_wrap .information::before {
            display: none
        }

        footer .footer_social {
            text-align: center;
            padding-right: 15px
        }

        footer .footer_social li {
            margin: 0px 10px
        }

        .phones, .navmenu {
            position: relative;
            left: -120px
        }

        .faq_wrap td {
            padding-bottom: 15px
        }

        .cont {
            width: 100%
        }

        .map_wrap {
            padding: 0px
        }

        .map_wrap .information table {
            margin: 24px 0px 29px
        }

        #date2 {
            min-width: 270px
        }

        .faq_bg {
            background-image: url(/assets/landing/images/faq_bg.webp);
            background-position: 60% 50%;
            background-repeat: no-repeat no-repeat
        }

        .slide_bg .info .sq_bg p {
            font-size: 17px
        }

        .contacts_bg {
            background-color: rgb(0, 0, 0) !important;
            background-position: initial initial !important;
            background-repeat: initial initial !important
        }
    }

    @media (max-width: 767px) and (min-width: 640px) {
        .block_li .li_left {
            width: 50%;
            float: left
        }

        .block_li .li_right {
            width: 50%;
            float: right
        }
    }

    @media (max-width: 767px) and (min-width: 568px) {
        .slide_bg .info .sq_bg {
            text-align: left;
            width: 50%;
            float: left
        }

        .slide_bg .info .sm12 {
            width: 60%;
            margin-left: 27%
        }

        footer .footer_menu li {
            display: inline-block !important
        }

        .window .header ul.menu li.menu-item a {
            font-size: 18px
        }
    }

    @media (max-width: 767px) {
        h2 {
            font-size: 30px !important
        }

        .navbar-brand {
            display: none;
            height: inherit;
            width: 75%;
            padding: 15px 15px 5px
        }

        .phones > li > a, .phones li {
            display: inline-block;
            padding: 0px 5px;
            margin-bottom: 5px;
            color: rgb(255, 255, 255) !important
        }

        .phones li img {
            position: relative;
            top: 5px;
            margin-right: 5px
        }

        .phones li.call a {
            padding: 8px 15px 10px;
            font-weight: bold;
            font-style: normal;
            font-variant: normal;
            font-size: 20px;
            line-height: normal;
            font-family: 'Yanone Kaffeesatz', sans-serif;
            text-transform: uppercase;
            border: 1px solid transparent;
            background-image: linear-gradient(to top, rgb(237, 178, 1), rgb(249, 191, 13), rgb(255, 206, 28)) !important;
            color: rgb(0, 0, 0) !important;
            background-position: initial initial !important;
            background-repeat: initial initial !important
        }

        .navbar-default .navbar-nav > li > a {
            color: rgb(255, 255, 255);
            text-transform: uppercase;
            text-align: center
        }

        .navbar-fixed-top {
            position: relative;
            margin-bottom: 0px
        }

        .main_block {
            margin: 20px 0px
        }

        .main_block h1 {
            text-align: center;
            font-size: 42px !important
        }

        .main_block .rent {
            text-align: center;
            margin: 20px 0px 10px
        }

        .main_block .rent img {
            width: 39px;
            float: none;
            margin-right: 0px !important
        }

        .main_block > .rent > p {
            text-align: center;
            font-size: 33px !important
        }

        .main_block > p {
            text-align: center;
            font-size: 16px !important
        }

        .slide_bg .info .sq_bg {
            text-align: left
        }

        .slide_bg .info .sq_bg p {
            margin-left: 20px;
            font-size: 14px
        }

        .about_bg .about {
            margin-top: 35px
        }

        .dots {
            display: none
        }

        .job_bg h2 {
            margin: 35px 0px 30px
        }

        .job_bg {
            background-color: rgb(229, 229, 229);
            height: auto;
            background-position: initial initial;
            background-repeat: initial initial
        }

        .jobs {
            text-align: center;
            margin-bottom: 20px
        }

        .faq_bg {
            background-color: rgb(0, 0, 0);
            height: auto;
            background-position: initial initial;
            background-repeat: initial initial
        }

        .faq_wrap h2 {
            margin: 40px 0px 25px
        }

        .faq_wrap .right span.none {
            display: none
        }

        .cap .text {
            min-height: 165px;
            max-height: 165px;
            overflow-y: scroll;
            margin-bottom: 20px
        }

        .cap .text::-webkit-scrollbar {
            width: 0px
        }

        .review_bg .owl-carousel .owl-item.center .cap {
            margin-top: 20px
        }

        .contacts_bg {
            background-color: rgb(0, 0, 0);
            height: auto;
            background-position: initial initial;
            background-repeat: initial initial
        }

        .map_wrap {
            padding: 0px
        }

        .map_wrap .contact h2 {
            text-align: center
        }

        .contact {
            height: auto;
            width: 100%;
            position: relative;
            top: 0px;
            left: 0px;
            padding: 25px 15px 10px;
            box-shadow: none
        }

        .map_wrap .information {
            height: auto;
            width: 100%;
            position: relative;
            top: 0px;
            right: 0px
        }

        .map_wrap .information::before {
            display: none
        }

        footer .footer_social {
            text-align: center;
            padding-right: 15px
        }

        footer li {
            margin: 0px 10px
        }

        footer p {
            text-align: center
        }

        footer .footer_menu {
            margin-top: 20px
        }

        footer .footer_menu li {
            display: block
        }

        .contact_us, #hidden-call, #hidden-order, #hidden-order .order, #hidden-order input.subm_order {
            width: 100%
        }

        #more.hiddens {
            visibility: hidden;
            overflow: hidden;
            height: 0px
        }

        .phones .down li {
            margin-bottom: 0px
        }
    }

    @media (max-width: 330px) {
        .xdsoft_datetimepicker, .xdsoft_noselect, .xdsoft_ {
            left: 0px !important
        }

        .contact_us .form-group i {
            width: 38px
        }

        .contact_us input {
            text-indent: 35px
        }
    }

    @media (max-width: 425px) {
        .navbar-fixed-top {
            position: fixed
        }
    }

    .main_block .rent img {
        margin-right: 26px !important
    }

    .main_block > p {
        font-size: 23px !important
    }

    @media (max-width: 1199px) and (min-width: 992px) {
        .navbar-brand img {
            width: 300px !important
        }
    }

    @media (max-width: 767px) {
        .slide_bg .info .sq_bg p {
            font-size: 13px !important
        }

        body .main_block .rent img {
            margin-right: 0px !important
        }

        body .main_block > p {
            font-size: 16px !important
        }
    }

    .owl-carousel, .owl-carousel .owl-item {
        position: relative
    }

    .owl-carousel {
        display: none;
        width: 100%;
        z-index: 1
    }

    .owl-carousel .owl-stage {
        position: relative
    }

    .owl-carousel .owl-stage::after {
        content: '.';
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0px
    }

    .owl-carousel .owl-stage-outer {
        position: relative;
        overflow: hidden;
        -webkit-transform: translate3d(0px, 0px, 0px)
    }

    .owl-carousel .owl-item {
        -webkit-backface-visibility: hidden;
        -webkit-transform: translate3d(0px, 0px, 0px)
    }

    .owl-carousel .owl-item {
        min-height: 1px;
        float: left;
        -webkit-backface-visibility: hidden
    }

    .owl-carousel .owl-item img {
        display: block;
        width: 100%
    }

    .owl-carousel .owl-nav.disabled {
        display: none
    }

    .owl-carousel.owl-loaded {
        display: block
    }

    .owl-theme .owl-dots, .owl-theme .owl-nav {
        text-align: center
    }

    .owl-theme .owl-nav {
        margin-top: 10px
    }

    .owl-theme .owl-nav [class*="owl-"] {
        color: rgb(255, 255, 255);
        font-size: 14px;
        margin: 5px;
        padding: 4px 7px;
        background-color: rgb(214, 214, 214);
        display: inline-block;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
        border-bottom-right-radius: 3px;
        border-bottom-left-radius: 3px;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .owl-theme .owl-nav.disabled + .owl-dots {
        margin-top: 10px
    }

    .owl-theme .owl-dots .owl-dot {
        display: inline-block;
        zoom: 1
    }

    .owl-theme .owl-dots .owl-dot span {
        width: 10px;
        height: 10px;
        margin: 5px 7px;
        background-color: rgb(214, 214, 214);
        display: block;
        -webkit-backface-visibility: visible;
        border-top-left-radius: 30px;
        border-top-right-radius: 30px;
        border-bottom-right-radius: 30px;
        border-bottom-left-radius: 30px;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .owl-theme .owl-dots .owl-dot.active span {
        background-color: rgb(134, 151, 145);
        background-position: initial initial;
        background-repeat: initial initial
    }

    @font-face {
        font-display: swap;
        font-family: FontAwesome;
        src: url(/assets/landing/fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format('embedded-opentype'), url(/assets/landing/fonts/fontawesome-webfont.woff2?v=4.7.0) format('woff2'), url(/assets/landing/fonts/fontawesome-webfont.woff?v=4.7.0) format('woff'), url(/assets/landing/fonts/fontawesome-webfont.ttf?v=4.7.0) format('truetype'), url(/assets/landing/fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular) format('svg');
        font-weight: normal;
        font-style: normal
    }

    .fa {
        display: inline-block;
        font-style: normal;
        font-variant: normal;
        font-weight: normal;
        line-height: 1;
        font-family: FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased
    }

    .fa-user::before {
        content: '\f007'
    }

    .fa-pencil::before {
        content: '\f040'
    }

    .fa-calendar::before {
        content: '\f073'
    }

    .fa-phone::before {
        content: '\f095'
    }

    .fa-facebook::before {
        content: '\f09a'
    }

    .fa-envelope::before {
        content: '\f0e0'
    }

    .fa-angle-down::before {
        content: '\f107'
    }

    .fa-youtube::before {
        content: '\f167'
    }

    .fa-instagram::before {
        content: '\f16d'
    }

    .sr-only {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0px;
        margin: -1px;
        overflow: hidden;
        clip: rect(0px 0px 0px 0px);
        border: 0px
    }

    .xdsoft_datetimepicker {
        box-shadow: rgba(0, 0, 0, 0.505882) 0px 5px 15px -5px;
        background-color: rgb(255, 255, 255);
        border-width: 1px;
        border-style: solid;
        border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(187, 187, 187);
        color: rgb(51, 51, 51);
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        padding: 2px 8px 8px 0px;
        position: absolute;
        z-index: 9999999;
        box-sizing: border-box;
        display: none;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .xdsoft_datetimepicker button {
        border: none !important
    }

    .xdsoft_datetimepicker * {
        box-sizing: border-box;
        padding: 0px;
        margin: 0px
    }

    .xdsoft_datetimepicker .xdsoft_datepicker, .xdsoft_datetimepicker .xdsoft_timepicker {
        display: none
    }

    .xdsoft_datetimepicker .xdsoft_datepicker.active {
        display: block
    }

    .xdsoft_datetimepicker .xdsoft_datepicker {
        width: 300px;
        float: left;
        margin-left: 8px
    }

    .xdsoft_datetimepicker .xdsoft_timepicker {
        width: 58px;
        float: left;
        text-align: center;
        margin-left: 8px;
        margin-top: 0px
    }

    .xdsoft_datetimepicker .xdsoft_datepicker.active + .xdsoft_timepicker {
        margin-top: 8px;
        margin-bottom: 3px
    }

    .xdsoft_datetimepicker .xdsoft_monthpicker {
        position: relative;
        text-align: center
    }

    .xdsoft_datetimepicker .xdsoft_label i, .xdsoft_datetimepicker .xdsoft_prev, .xdsoft_datetimepicker .xdsoft_next, .xdsoft_datetimepicker .xdsoft_today_button {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAAAeCAYAAADaW7vzAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6Q0NBRjI1NjM0M0UwMTFFNDk4NkFGMzJFQkQzQjEwRUIiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6Q0NBRjI1NjQ0M0UwMTFFNDk4NkFGMzJFQkQzQjEwRUIiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDpDQ0FGMjU2MTQzRTAxMUU0OTg2QUYzMkVCRDNCMTBFQiIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpDQ0FGMjU2MjQzRTAxMUU0OTg2QUYzMkVCRDNCMTBFQiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PoNEP54AAAIOSURBVHja7Jq9TsMwEMcxrZD4WpBYeKUCe+kTMCACHZh4BFfHO/AAIHZGFhYkBBsSEqxsLCAgXKhbXYOTxh9pfJVP+qutnZ5s/5Lz2Y5I03QhWji2GIcgAokWgfCxNvcOCCGKqiSqhUp0laHOne05vdEyGMfkdxJDVjgwDlEQgYQBgx+ULJaWSXXS6r/ER5FBVR8VfGftTKcITNs+a1XpcFoExREIDF14AVIFxgQUS+h520cdud6wNkC0UBw6BCO/HoCYwBhD8QCkQ/x1mwDyD4plh4D6DDV0TAGyo4HcawLIBBSLDkHeH0Mg2yVP3l4TQMZQDDsEOl/MgHQqhMNuE0D+oBh0CIr8MAKyazBH9WyBuKxDWgbXfjNf32TZ1KWm/Ap1oSk/R53UtQ5xTh3LUlMmT8gt6g51Q9p+SobxgJQ/qmsfZhWywGFSl0yBjCLJCMgXail3b7+rumdVJ2YRss4cN+r6qAHDkPWjPjdJCF4n9RmAD/V9A/Wp4NQassDjwlB6XBiCxcJQWmZZb8THFilfy/lfrTvLghq2TqTHrRMTKNJ0sIhdo15RT+RpyWwFdY96UZ/LdQKBGjcXpcc1AlSFEfLmouD+1knuxBDUVrvOBmoOC/rEcN7OQxKVeJTCiAdUzUJhA2Oez9QTkp72OTVcxDcXY8iKNkxGAJXmJCOQwOa6dhyXsOa6XwEGAKdeb5ET3rQdAAAAAElFTkSuQmCC)
    }

    .xdsoft_datetimepicker .xdsoft_label i {
        opacity: 0.5;
        display: inline-block;
        width: 9px;
        height: 20px;
        vertical-align: middle;
        background-position: -92px -19px
    }

    .xdsoft_datetimepicker .xdsoft_prev {
        float: left;
        background-position: -20px 0px
    }

    .xdsoft_datetimepicker .xdsoft_today_button {
        float: left;
        margin-left: 5px;
        background-position: -70px 0px
    }

    .xdsoft_datetimepicker .xdsoft_next {
        float: right;
        background-position: 0px 0px
    }

    .xdsoft_datetimepicker .xdsoft_next, .xdsoft_datetimepicker .xdsoft_prev, .xdsoft_datetimepicker .xdsoft_today_button {
        background-color: transparent;
        border: 0px none;
        display: block;
        height: 30px;
        opacity: 0.5;
        outline: none medium;
        overflow: hidden;
        padding: 0px;
        position: relative;
        text-indent: 100%;
        white-space: nowrap;
        width: 20px;
        min-width: 0px;
        background-repeat: no-repeat no-repeat
    }

    .xdsoft_datetimepicker .xdsoft_timepicker .xdsoft_prev, .xdsoft_datetimepicker .xdsoft_timepicker .xdsoft_next {
        float: none;
        height: 15px;
        width: 30px;
        display: block;
        margin-left: 14px;
        margin-top: 7px;
        background-position: -40px -15px
    }

    .xdsoft_datetimepicker .xdsoft_timepicker .xdsoft_prev {
        margin-bottom: 7px;
        margin-top: 0px;
        background-position: -40px 0px
    }

    .xdsoft_datetimepicker .xdsoft_timepicker .xdsoft_time_box {
        height: 151px;
        overflow: hidden;
        border-bottom-width: 1px;
        border-bottom-style: solid;
        border-bottom-color: rgb(221, 221, 221)
    }

    .xdsoft_datetimepicker .xdsoft_timepicker .xdsoft_time_box > div > div {
        background-color: rgb(245, 245, 245);
        border-top-width: 1px;
        border-top-style: solid;
        border-top-color: rgb(221, 221, 221);
        color: rgb(102, 102, 102);
        font-size: 12px;
        text-align: center;
        border-collapse: collapse;
        border-bottom-width: 0px;
        height: 25px;
        line-height: 25px;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .xdsoft_datetimepicker .xdsoft_timepicker .xdsoft_time_box > div > div:first-child {
        border-top-width: 0px
    }

    .xdsoft_datetimepicker .xdsoft_label {
        display: inline;
        position: relative;
        z-index: 9999;
        margin: 0px;
        padding: 5px 3px;
        font-size: 14px;
        line-height: 20px;
        font-weight: bold;
        background-color: rgb(255, 255, 255);
        float: left;
        width: 182px;
        text-align: center
    }

    .xdsoft_datetimepicker .xdsoft_label > .xdsoft_select {
        border: 1px solid rgb(204, 204, 204);
        position: absolute;
        right: 0px;
        top: 30px;
        z-index: 101;
        display: none;
        background-color: rgb(255, 255, 255);
        max-height: 160px;
        overflow-y: hidden;
        background-position: initial initial;
        background-repeat: initial initial
    }

    .xdsoft_datetimepicker .xdsoft_label > .xdsoft_select.xdsoft_monthselect {
        right: -7px
    }

    .xdsoft_datetimepicker .xdsoft_label > .xdsoft_select.xdsoft_yearselect {
        right: 2px
    }

    .xdsoft_datetimepicker .xdsoft_month {
        width: 100px;
        text-align: right
    }

    .xdsoft_datetimepicker .xdsoft_calendar {
        clear: both
    }

    .xdsoft_datetimepicker .xdsoft_year {
        width: 48px;
        margin-left: 5px
    }

    .xdsoft_time_box {
        position: relative;
        border: 1px solid rgb(204, 204, 204)
    }

    .xdsoft_scrollbar > .xdsoft_scroller {
        height: 20px;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
        border-bottom-right-radius: 3px;
        border-bottom-left-radius: 3px;
        background-color: rgb(204, 204, 204) !important;
        background-position: initial initial !important;
        background-repeat: initial initial !important
    }

    .xdsoft_scrollbar {
        position: absolute;
        width: 7px;
        right: 0px;
        top: 0px;
        bottom: 0px
    }

    .xdsoft_scroller_box {
        position: relative
    }

    .xdsoft_datetimepicker .xdsoft_save_selected {
        display: block;
        margin-top: 5px;
        width: 100%;
        color: rgb(69, 69, 81);
        font-size: 13px;
        border: 1px solid rgb(221, 221, 221) !important
    }

    .xdsoft_datetimepicker .blue-gradient-button {
        font-family: museo-sans, 'Book Antiqua', sans-serif;
        font-size: 12px;
        font-weight: 300;
        color: rgb(130, 135, 140);
        height: 28px;
        position: relative;
        padding: 4px 17px 4px 33px;
        border: 1px solid rgb(215, 216, 218);
        background-image: linear-gradient(rgb(255, 255, 255) 0%, rgb(244, 248, 250) 73%);
        background-position: initial initial;
        background-repeat: initial initial
    }</style>